# Introduction to Pandas, CSV and DateTime

Python provides several powerful libraries that simplify tasks like data analysis, such as Pandas and its DataFrame data structure. Alongside this, handling CSV files and working with DateTime objects are essential skills for data processing.


- - -

## Table of Contents
* [DataFrames in Pandas](#intro)
    1. [Constructors and conversion](#constructorsconversion)
    2. [Getting basic information](#basicinfos)
    3. [Access and modify data basicinfos](#accessdata)
    * [Handling missing data](#handlingmissingvalues)
    * [Checking for missing values](#checkingmissingvalues)
    * [Manipulating columns of a DataFrame](#manipulatingcolumns)
    * [Manipulating rows of a data frame](#manipulatingrows)
    * [Joining data frames](#joindata)
* [CSV.jl](#csv)
    * [Reading data from a .csv file](#readdata)
* [DateTime](#datetime)

- - - -

# DataFrames in Pandas <a class="anchor" id="intro"></a>

In data manipulation and analysis, Pandas stands as one of the most popular Python libraries, primarily due to its DataFrames. A DataFrame is a two-dimensional data structure, akin to a table in SQL or a sheet in an Excel workbook. It comprises rows and columns that can hold a variety of data types, such as integers, strings, and floats, amongst others.

    Pandas = library
    DataFrame = data structure
    
In this section we need `Pandas` and `NumPy`

In [1]:
import pandas as pd # pd is an often used alias
import numpy as np
import datetime

---

## Constructors and conversion <a class="anchor" id="constructorsconversion"></a>


### Create DataFrame

In [2]:
# Create DataFrame with dictionary

data = {
    'apples': [3, 2, 0, 1], 
    'sizes': [3.4, 3.2, 3.9, 2.9],
    'color': ["green", "green", "red", "green"]
}

purchases_df = pd.DataFrame(data)

print(purchases_df)

   apples  sizes  color
0       3    3.4  green
1       2    3.2  green
2       0    3.9    red
3       1    2.9  green

In [3]:
# Create DataFrame from matrix / 2D array

import numpy as np

array_2d = np.array([[8,9],
                     [7,6]])

purchases_df = pd.DataFrame(array_2d)

print(purchases_df)

   0  1
0  8  9
1  7  6

`Importing CSV files` into your project is a common method to create a DataFrame. The content of a .csv file looks like this:

    "Date","Product","Category","Units Sold","Unit Price","Total Sales"
    "2023-01-02","Widget A","Electronics",3,50,150
    "2023-01-03","Widget B","Electronics",5,70,350
    "2023-01-05","Widget C","Home Appliances",1,200,200
    ...

In [4]:
# Create DataFrame from CSV File (common method)

purchases_df = pd.read_csv("data/jan_sales.csv")

print(purchases_df) #whole dataset

          Date   Product         Category  Units Sold  Unit Price  Total Sales
0   2023-01-02  Widget A      Electronics           3          50          150
1   2023-01-03  Widget B      Electronics           5          70          350
2   2023-01-05  Widget C  Home Appliances           1         200          200
3   2023-01-06  Widget D         Clothing          10          30          300
4   2023-01-07  Widget E         Clothing           2         100          200
5   2023-01-09  Widget F  Home Appliances           4         150          600
6   2023-01-10  Widget G      Electronics           6          80          480
7   2023-01-12  Widget H         Clothing           8          40          320
8   2023-01-13  Widget I  Home Appliances           2         250          500
9   2023-01-15  Widget J      Electronics           7          60          420
10  2023-01-16  Widget A      Electronics           5          50          250
11  2023-01-18  Widget B      Electronics           4          70          280
12  2023-01-19  Widget C  Home Appliances           3         200          600
13  2023-01-20  Widget D         Clothing           5          30          150
14  2023-01-22  Widget E         Clothing           1         100          100
15  2023-01-23  Widget F  Home Appliances           6         150          900
16  2023-01-25  Widget G      Electronics           4          80          320
17  2023-01-26  Widget H         Clothing           7          40          280
18  2023-01-27  Widget I  Home Appliances           3         250          750
19  2023-01-29  Widget J      Electronics           8          60          480

In [5]:
# Load JSON file into a DataFrame

purchases_json_df = pd.read_json("data/jan_sales.json")

print(purchases_json_df)

         Date   Product         Category  Units Sold  Unit Price  Total Sales
0  2023-01-02  Widget A      Electronics           3          50          150
1  2023-01-03  Widget B      Electronics           5          70          350
2  2023-01-05  Widget C  Home Appliances           1         200          200
3  2023-01-06  Widget D         Clothing          10          30          300
4  2023-01-07  Widget E         Clothing           2         100          200
5  2023-01-09  Widget F  Home Appliances           4         150          600
6  2023-01-10  Widget G      Electronics           6          80          480
7  2023-01-12  Widget H         Clothing           8          40          320
8  2023-01-13  Widget I  Home Appliances           2         250          500
9  2023-01-15  Widget J      Electronics           7          60          420
10 2023-01-16  Widget A      Electronics           5          50          250
11 2023-01-18  Widget B      Electronics           4          70          280
12 2023-01-19  Widget C  Home Appliances           3         200          600
13 2023-01-20  Widget D         Clothing           5          30          150
14 2023-01-22  Widget E         Clothing           1         100          100
15 2023-01-23  Widget F  Home Appliances           6         150          900
16 2023-01-25  Widget G      Electronics           4          80          320
17 2023-01-26  Widget H         Clothing           7          40          280
18 2023-01-27  Widget I  Home Appliances           3         250          750
19 2023-01-29  Widget J      Electronics           8          60          480

In [6]:
# Copy existing DataFrame

df_copy = purchases_df.copy() # "deep" copy: data is actually duplicated in memory.

print(df_copy)

          Date   Product         Category  Units Sold  Unit Price  Total Sales
0   2023-01-02  Widget A      Electronics           3          50          150
1   2023-01-03  Widget B      Electronics           5          70          350
2   2023-01-05  Widget C  Home Appliances           1         200          200
3   2023-01-06  Widget D         Clothing          10          30          300
4   2023-01-07  Widget E         Clothing           2         100          200
5   2023-01-09  Widget F  Home Appliances           4         150          600
6   2023-01-10  Widget G      Electronics           6          80          480
7   2023-01-12  Widget H         Clothing           8          40          320
8   2023-01-13  Widget I  Home Appliances           2         250          500
9   2023-01-15  Widget J      Electronics           7          60          420
10  2023-01-16  Widget A      Electronics           5          50          250
11  2023-01-18  Widget B      Electronics           4          70          280
12  2023-01-19  Widget C  Home Appliances           3         200          600
13  2023-01-20  Widget D         Clothing           5          30          150
14  2023-01-22  Widget E         Clothing           1         100          100
15  2023-01-23  Widget F  Home Appliances           6         150          900
16  2023-01-25  Widget G      Electronics           4          80          320
17  2023-01-26  Widget H         Clothing           7          40          280
18  2023-01-27  Widget I  Home Appliances           3         250          750
19  2023-01-29  Widget J      Electronics           8          60          480

---

### Convert DataFrame to Matrix

To work with matrizes (/ 2D Arrays), we need to import numpy

In [7]:
purchases_df = pd.read_csv("data/jan_sales.csv") # create DataFrame

purchases_matrix = purchases_df.values # converted to matrix
# or
purchases_matrix = purchases_df.to_numpy() # works eqiuvalent

print(purchases_matrix)

[['2023-01-02' 'Widget A' 'Electronics' 3 50 150]
 ['2023-01-03' 'Widget B' 'Electronics' 5 70 350]
 ['2023-01-05' 'Widget C' 'Home Appliances' 1 200 200]
 ['2023-01-06' 'Widget D' 'Clothing' 10 30 300]
 ['2023-01-07' 'Widget E' 'Clothing' 2 100 200]
 ['2023-01-09' 'Widget F' 'Home Appliances' 4 150 600]
 ['2023-01-10' 'Widget G' 'Electronics' 6 80 480]
 ['2023-01-12' 'Widget H' 'Clothing' 8 40 320]
 ['2023-01-13' 'Widget I' 'Home Appliances' 2 250 500]
 ['2023-01-15' 'Widget J' 'Electronics' 7 60 420]
 ['2023-01-16' 'Widget A' 'Electronics' 5 50 250]
 ['2023-01-18' 'Widget B' 'Electronics' 4 70 280]
 ['2023-01-19' 'Widget C' 'Home Appliances' 3 200 600]
 ['2023-01-20' 'Widget D' 'Clothing' 5 30 150]
 ['2023-01-22' 'Widget E' 'Clothing' 1 100 100]
 ['2023-01-23' 'Widget F' 'Home Appliances' 6 150 900]
 ['2023-01-25' 'Widget G' 'Electronics' 4 80 320]
 ['2023-01-26' 'Widget H' 'Clothing' 7 40 280]
 ['2023-01-27' 'Widget I' 'Home Appliances' 3 250 750]
 ['2023-01-29' 'Widget J' 'Electronics' 8 60 480]]

---

## Getting basic information <a class="anchor" id="basicinfos"></a>

First, let's create a DataFrame.

In [8]:
purchases_df = pd.read_csv("data/jan_sales.csv") # create DataFrame

In [9]:
purchases_df.head() # Output first 5 rows .head(), .tail(), .info(), and .describe().

         Date   Product         Category  Units Sold  Unit Price  Total Sales
0  2023-01-02  Widget A      Electronics           3          50          150
1  2023-01-03  Widget B      Electronics           5          70          350
2  2023-01-05  Widget C  Home Appliances           1         200          200
3  2023-01-06  Widget D         Clothing          10          30          300
4  2023-01-07  Widget E         Clothing           2         100          200

In [10]:
purchases_df.head(3) # Output first 3 rows

         Date   Product         Category  Units Sold  Unit Price  Total Sales
0  2023-01-02  Widget A      Electronics           3          50          150
1  2023-01-03  Widget B      Electronics           5          70          350
2  2023-01-05  Widget C  Home Appliances           1         200          200

In [11]:
purchases_df.tail() # Output last 5 rows

          Date   Product         Category  Units Sold  Unit Price  Total Sales
15  2023-01-23  Widget F  Home Appliances           6         150          900
16  2023-01-25  Widget G      Electronics           4          80          320
17  2023-01-26  Widget H         Clothing           7          40          280
18  2023-01-27  Widget I  Home Appliances           3         250          750
19  2023-01-29  Widget J      Electronics           8          60          480

In [12]:
purchases_df.info() # Get information, especially on the columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         20 non-null     object
 1   Product      20 non-null     object
 2   Category     20 non-null     object
 3   Units Sold   20 non-null     int64
 4   Unit Price   20 non-null     int64
 5   Total Sales  20 non-null     int64
dtypes: int64(3), object(3)
memory usage: 1.1+ KB

In [13]:
purchases_df.describe() # generate descriptive statistics

       Units Sold  Unit Price  Total Sales
count   20.000000   20.000000    20.000000
mean     4.700000  103.000000   381.500000
std      2.473012   71.679109   210.319932
min      1.000000   30.000000   100.000000
25%      3.000000   50.000000   237.500000
50%      4.500000   75.000000   320.000000
75%      6.250000  150.000000   485.000000
max     10.000000  250.000000   900.000000

In [14]:
purchases_df.shape # get the shape

# shape is a property not a method of a DataFrame Obj.; that's why we use '.shape' instead of '.shape()'

(20, 6)

In [15]:
purchases_df.columns #get columns only

Index(['Date', 'Product', 'Category', 'Units Sold', 'Unit Price',
       'Total Sales'],
      dtype='object')

---

## Access and modify data basicinfos <a class="anchor" id="accessdata"></a>

Let's create our `DataFrame`

In [16]:
my_df = pd.read_csv("data/jan_sales.csv")
my_df.head(5)

         Date   Product         Category  Units Sold  Unit Price  Total Sales
0  2023-01-02  Widget A      Electronics           3          50          150
1  2023-01-03  Widget B      Electronics           5          70          350
2  2023-01-05  Widget C  Home Appliances           1         200          200
3  2023-01-06  Widget D         Clothing          10          30          300
4  2023-01-07  Widget E         Clothing           2         100          200

---

### Sort DataFrame

In [17]:
my_df.sort_values(by='Product')

          Date   Product         Category  Units Sold  Unit Price  Total Sales
0   2023-01-02  Widget A      Electronics           3          50          150
10  2023-01-16  Widget A      Electronics           5          50          250
1   2023-01-03  Widget B      Electronics           5          70          350
11  2023-01-18  Widget B      Electronics           4          70          280
2   2023-01-05  Widget C  Home Appliances           1         200          200
12  2023-01-19  Widget C  Home Appliances           3         200          600
3   2023-01-06  Widget D         Clothing          10          30          300
13  2023-01-20  Widget D         Clothing           5          30          150
4   2023-01-07  Widget E         Clothing           2         100          200
14  2023-01-22  Widget E         Clothing           1         100          100
5   2023-01-09  Widget F  Home Appliances           4         150          600
15  2023-01-23  Widget F  Home Appliances           6         150          900
6   2023-01-10  Widget G      Electronics           6          80          480
16  2023-01-25  Widget G      Electronics           4          80          320
17  2023-01-26  Widget H         Clothing           7          40          280
7   2023-01-12  Widget H         Clothing           8          40          320
18  2023-01-27  Widget I  Home Appliances           3         250          750
8   2023-01-13  Widget I  Home Appliances           2         250          500
9   2023-01-15  Widget J      Electronics           7          60          420
19  2023-01-29  Widget J      Electronics           8          60          480

---

### Subsetting one column with [ ]

In [18]:
my_df["Date"] # return a single column; Output: Pandas Series

0     2023-01-02
1     2023-01-03
2     2023-01-05
3     2023-01-06
4     2023-01-07
5     2023-01-09
6     2023-01-10
7     2023-01-12
8     2023-01-13
9     2023-01-15
10    2023-01-16
11    2023-01-18
12    2023-01-19
13    2023-01-20
14    2023-01-22
15    2023-01-23
16    2023-01-25
17    2023-01-26
18    2023-01-27
19    2023-01-29
Name: Date, dtype: object

---

### Subsetting multiple columns with [[ ]]

In [19]:
my_df[["Date", "Total Sales"]] # Provide a list to return multiple columns; Output: Pandas DataFrame

          Date  Total Sales
0   2023-01-02          150
1   2023-01-03          350
2   2023-01-05          200
3   2023-01-06          300
4   2023-01-07          200
5   2023-01-09          600
6   2023-01-10          480
7   2023-01-12          320
8   2023-01-13          500
9   2023-01-15          420
10  2023-01-16          250
11  2023-01-18          280
12  2023-01-19          600
13  2023-01-20          150
14  2023-01-22          100
15  2023-01-23          900
16  2023-01-25          320
17  2023-01-26          280
18  2023-01-27          750
19  2023-01-29          480

---

### Subsetting rows (and columns) with .loc and .iloc

In [20]:
my_df.iloc[0] # get the row with position 0

Date            2023-01-02
Product           Widget A
Category       Electronics
Units Sold               3
Unit Price              50
Total Sales            150
Name: 0, dtype: object

In [21]:
my_df.iloc[0:5] # get the rows with position 0 to 5 (excl.)

         Date   Product         Category  Units Sold  Unit Price  Total Sales
0  2023-01-02  Widget A      Electronics           3          50          150
1  2023-01-03  Widget B      Electronics           5          70          350
2  2023-01-05  Widget C  Home Appliances           1         200          200
3  2023-01-06  Widget D         Clothing          10          30          300
4  2023-01-07  Widget E         Clothing           2         100          200

In [22]:
my_df.iloc[[0,5,10]] # get the rows with position 0, 5 and 10

          Date   Product         Category  Units Sold  Unit Price  Total Sales
0   2023-01-02  Widget A      Electronics           3          50          150
5   2023-01-09  Widget F  Home Appliances           4         150          600
10  2023-01-16  Widget A      Electronics           5          50          250

In [23]:
my_df.iloc[0:5,0:3] # get columns 0, 1 and 2 for the rows with position 0-5

         Date   Product         Category
0  2023-01-02  Widget A      Electronics
1  2023-01-03  Widget B      Electronics
2  2023-01-05  Widget C  Home Appliances
3  2023-01-06  Widget D         Clothing
4  2023-01-07  Widget E         Clothing

In [24]:
my_df.loc[0:5, ["Date","Product","Category"]] # alternatively with .loc to use labels instead of the integer locations

         Date   Product         Category
0  2023-01-02  Widget A      Electronics
1  2023-01-03  Widget B      Electronics
2  2023-01-05  Widget C  Home Appliances
3  2023-01-06  Widget D         Clothing
4  2023-01-07  Widget E         Clothing
5  2023-01-09  Widget F  Home Appliances

In [25]:
my_df.iloc[0:5,:] # get all columns for the rows with position 0-5

         Date   Product         Category  Units Sold  Unit Price  Total Sales
0  2023-01-02  Widget A      Electronics           3          50          150
1  2023-01-03  Widget B      Electronics           5          70          350
2  2023-01-05  Widget C  Home Appliances           1         200          200
3  2023-01-06  Widget D         Clothing          10          30          300
4  2023-01-07  Widget E         Clothing           2         100          200

In [26]:
my_df.iloc[:,:] # get whole table

          Date   Product         Category  Units Sold  Unit Price  Total Sales
0   2023-01-02  Widget A      Electronics           3          50          150
1   2023-01-03  Widget B      Electronics           5          70          350
2   2023-01-05  Widget C  Home Appliances           1         200          200
3   2023-01-06  Widget D         Clothing          10          30          300
4   2023-01-07  Widget E         Clothing           2         100          200
5   2023-01-09  Widget F  Home Appliances           4         150          600
6   2023-01-10  Widget G      Electronics           6          80          480
7   2023-01-12  Widget H         Clothing           8          40          320
8   2023-01-13  Widget I  Home Appliances           2         250          500
9   2023-01-15  Widget J      Electronics           7          60          420
10  2023-01-16  Widget A      Electronics           5          50          250
11  2023-01-18  Widget B      Electronics           4          70          280
12  2023-01-19  Widget C  Home Appliances           3         200          600
13  2023-01-20  Widget D         Clothing           5          30          150
14  2023-01-22  Widget E         Clothing           1         100          100
15  2023-01-23  Widget F  Home Appliances           6         150          900
16  2023-01-25  Widget G      Electronics           4          80          320
17  2023-01-26  Widget H         Clothing           7          40          280
18  2023-01-27  Widget I  Home Appliances           3         250          750
19  2023-01-29  Widget J      Electronics           8          60          480

---

### Boolean Indexing

In [27]:
my_df[ my_df["Product"] == "Widget A" ] # return all rows with "Widget A" in "Product"

          Date   Product     Category  Units Sold  Unit Price  Total Sales
0   2023-01-02  Widget A  Electronics           3          50          150
10  2023-01-16  Widget A  Electronics           5          50          250

In [28]:
my_df[ my_df["Units Sold"] >= 7 ] # return all rows with more than or equal to 7 units sold

          Date   Product     Category  Units Sold  Unit Price  Total Sales
3   2023-01-06  Widget D     Clothing          10          30          300
7   2023-01-12  Widget H     Clothing           8          40          320
9   2023-01-15  Widget J  Electronics           7          60          420
17  2023-01-26  Widget H     Clothing           7          40          280
19  2023-01-29  Widget J  Electronics           8          60          480

In [29]:
my_df[ (my_df["Units Sold"] >= 5) & (my_df["Product"] == "Widget A") ] # with multiple conditions

          Date   Product     Category  Units Sold  Unit Price  Total Sales
10  2023-01-16  Widget A  Electronics           5          50          250

- - - 

## Handling Missing Values <a class="anchor" id="handlingmissingvalues"></a>

In Python, particularly with pandas and NumPy, handling missing values is facilitated by the usage of `NaN` (Not a Number) and `None` to represent such values. The pandas library provides various functions to manage, identify, and impute these missing values in a DataFrame.

- Identifying and Representing Missing Values
- Detecting Missing Values
- Managing Missing Values

In [30]:
import pandas as pd
import numpy as np

In [31]:
# A missing value is typically represented as NaN in Python, within a NumPy array or a pandas DataFrame.
missing_value = np.nan
type(missing_value)

float

Arrays (or lists) and DataFrames in Python can contain `NaN` values, which might necessitate handling or imputing these missing values before performing certain operations.

In [32]:
# Example array with missing values
x = [1, 2, np.nan, 3]

# Creating a DataFrame with missing values
df1 = pd.DataFrame({'a': [1, 2, np.nan], 'b': ['a', 'b', None]})

To check for missing values in Python, `isna()` or `isnull()` can be used for a DataFrame, and `np.isnan()` for a NumPy array.

- - - 

# Checking for missing values <a class="anchor" id="checkingmissingvalues"></a>
pd.isna(1), pd.isna(np.nan), pd.isna(x), df1.isna()

To ignore or skip missing values in a list or array, you might filter them out explicitly.

In [33]:
# Skipping missing values
[i for i in [1, np.nan, 2, np.nan] if not pd.isna(i)]

[1, 2]

You can replace `NaN` or `None` values using `replace()` in pandas, which returns a new object with the missing values replaced by a specified value.

In [34]:
# Replacing missing values
df1.replace(np.nan, value=-1)

     a   b
0  1.0   a
1  2.0   b
2 -1.0  -1

When dealing with DataFrames, you can modify them in place using `inplace=True` in certain functions like `replace()`, which avoids the need to assign the result back to a variable.

In [35]:
# Replacing values in-place in a DataFrame column
df1['a'].replace(np.nan, value=100, inplace=True)

To remove rows containing missing values from a DataFrame, `dropna()` can be utilized. The `inplace` parameter determines whether the operation is performed in-place or a new DataFrame is returned.

In [36]:
# Removing rows with missing values
y = df1.dropna()
df1.dropna(inplace=True)

---

## Manipulating columns of a DataFrame <a class="anchor" id="manipulatingcolumns"></a>

### Rename

In [37]:
my_df.rename(columns={"Date": "New_Date"})

      New_Date   Product         Category  Units Sold  Unit Price  Total Sales
0   2023-01-02  Widget A      Electronics           3          50          150
1   2023-01-03  Widget B      Electronics           5          70          350
2   2023-01-05  Widget C  Home Appliances           1         200          200
3   2023-01-06  Widget D         Clothing          10          30          300
4   2023-01-07  Widget E         Clothing           2         100          200
5   2023-01-09  Widget F  Home Appliances           4         150          600
6   2023-01-10  Widget G      Electronics           6          80          480
7   2023-01-12  Widget H         Clothing           8          40          320
8   2023-01-13  Widget I  Home Appliances           2         250          500
9   2023-01-15  Widget J      Electronics           7          60          420
10  2023-01-16  Widget A      Electronics           5          50          250
11  2023-01-18  Widget B      Electronics           4          70          280
12  2023-01-19  Widget C  Home Appliances           3         200          600
13  2023-01-20  Widget D         Clothing           5          30          150
14  2023-01-22  Widget E         Clothing           1         100          100
15  2023-01-23  Widget F  Home Appliances           6         150          900
16  2023-01-25  Widget G      Electronics           4          80          320
17  2023-01-26  Widget H         Clothing           7          40          280
18  2023-01-27  Widget I  Home Appliances           3         250          750
19  2023-01-29  Widget J      Electronics           8          60          480

### Add

In [38]:
my_df["Location"] = "GER"

my_df.head()

,Date,Product,Category,Units Sold,Unit Price,Total Sales,Location
0,2023-01-02,Widget A,Electronics,3,50,150,GER
1,2023-01-03,Widget B,Electronics,5,70,350,GER
2,2023-01-05,Widget C,Home Appliances,1,200,200,GER
3,2023-01-06,Widget D,Clothing,10,30,300,GER
4,2023-01-07,Widget E,Clothing,2,100,200,GER

In [39]:
my_df[["City","Street"]] = ["Berlin","Street 1"]
my_df.head()

,Date,Product,Category,Units Sold,Unit Price,Total Sales,Location,City,Street
0,2023-01-02,Widget A,Electronics,3,50,150,GER,Berlin,Street 1
1,2023-01-03,Widget B,Electronics,5,70,350,GER,Berlin,Street 1
2,2023-01-05,Widget C,Home Appliances,1,200,200,GER,Berlin,Street 1
3,2023-01-06,Widget D,Clothing,10,30,300,GER,Berlin,Street 1
4,2023-01-07,Widget E,Clothing,2,100,200,GER,Berlin,Street 1

### Remove

In [40]:
my_df = my_df.drop(columns=["City","Street"]) #overwrite 'my_df' to keep the changes

my_df.head()

,Date,Product,Category,Units Sold,Unit Price,Total Sales,Location
0,2023-01-02,Widget A,Electronics,3,50,150,GER
1,2023-01-03,Widget B,Electronics,5,70,350,GER
2,2023-01-05,Widget C,Home Appliances,1,200,200,GER
3,2023-01-06,Widget D,Clothing,10,30,300,GER
4,2023-01-07,Widget E,Clothing,2,100,200,GER

### Merge

In [41]:
# Creating DataFrame df1
df1 = pd.DataFrame({
    'ID': [1, 2, 3, 4, 5],
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eva']
})

# Creating DataFrame df2
df2 = pd.DataFrame({
    'ID': [3, 4, 5, 6, 7],
    'Age': [25, 30, 35, 40, 45]
})

# Merging df1 and df2 on 'ID'
merged_df = df1.merge(df2, on='ID')

merged_df

   ID     Name  Age
0   3  Charlie   25
1   4    Diana   30
2   5      Eva   35

### Subsetting

In [42]:
# Select a single column
name_column = my_df["Product"]

name_column

0     Widget A
1     Widget B
2     Widget C
3     Widget D
4     Widget E
5     Widget F
6     Widget G
7     Widget H
8     Widget I
9     Widget J
10    Widget A
11    Widget B
12    Widget C
13    Widget D
14    Widget E
15    Widget F
16    Widget G
17    Widget H
18    Widget I
19    Widget J
Name: Product, dtype: object

In [43]:
#Select multiple columns
selected_columns = my_df[["Product", "Units Sold"]]

selected_columns

     Product  Units Sold
0   Widget A           3
1   Widget B           5
2   Widget C           1
3   Widget D          10
4   Widget E           2
5   Widget F           4
6   Widget G           6
7   Widget H           8
8   Widget I           2
9   Widget J           7
10  Widget A           5
11  Widget B           4
12  Widget C           3
13  Widget D           5
14  Widget E           1
15  Widget F           6
16  Widget G           4
17  Widget H           7
18  Widget I           3
19  Widget J           8

---

## Manipulating rows of a DataFrame <a class="anchor" id="manipulatingrows"></a>

### Add

In [44]:
# create row
new_row = pd.DataFrame({
    'Date': ["2023-01-29"],
    'Product': ["Widget G"],
    'Category': ["Clothing"],
    'Unit Price': [80.0]
})  

new_df = pd.concat([my_df, new_row], ignore_index=True)  # 'ignore_index=True' is used to reset the index of the resulting DataFrame

new_df.tail() # show last 5 rows

,Date,Product,Category,Units Sold,Unit Price,Total Sales,Location
16,2023-01-25,Widget G,Electronics,4.0,80.0,320.0,GER
17,2023-01-26,Widget H,Clothing,7.0,40.0,280.0,GER
18,2023-01-27,Widget I,Home Appliances,3.0,250.0,750.0,GER
19,2023-01-29,Widget J,Electronics,8.0,60.0,480.0,GER
20,2023-01-29,Widget G,Clothing,NaN,80.0,NaN,NaN

### Remove

In [45]:
new_df.drop(10) # drop single row

,Date,Product,Category,Units Sold,Unit Price,Total Sales,Location
0,2023-01-02,Widget A,Electronics,3.0,50.0,150.0,GER
1,2023-01-03,Widget B,Electronics,5.0,70.0,350.0,GER
2,2023-01-05,Widget C,Home Appliances,1.0,200.0,200.0,GER
3,2023-01-06,Widget D,Clothing,10.0,30.0,300.0,GER
4,2023-01-07,Widget E,Clothing,2.0,100.0,200.0,GER
5,2023-01-09,Widget F,Home Appliances,4.0,150.0,600.0,GER
6,2023-01-10,Widget G,Electronics,6.0,80.0,480.0,GER
7,2023-01-12,Widget H,Clothing,8.0,40.0,320.0,GER
8,2023-01-13,Widget I,Home Appliances,2.0,250.0,500.0,GER
9,2023-01-15,Widget J,Electronics,7.0,60.0,420.0,GER
11,2023-01-18,Widget B,Electronics,4.0,70.0,280.0,GER
12,2023-01-19,Widget C,Home Appliances,3.0,200.0,600.0,GER
13,2023-01-20,Widget D,Clothing,5.0,30.0,150.0,GER
14,2023-01-22,Widget E,Clothing,1.0,100.0,100.0,GER
15,2023-01-23,Widget F,Home Appliances,6.0,150.0,900.0,GER
16,2023-01-25,Widget G,Electronics,4.0,80.0,320.0,GER
17,2023-01-26,Widget H,Clothing,7.0,40.0,280.0,GER
18,2023-01-27,Widget I,Home Appliances,3.0,250.0,750.0,GER
19,2023-01-29,Widget J,Electronics,8.0,60.0,480.0,GER
20,2023-01-29,Widget G,Clothing,NaN,80.0,NaN,NaN

In [46]:
new_df.drop(range(10,15)) # drop multiple rows

,Date,Product,Category,Units Sold,Unit Price,Total Sales,Location
0,2023-01-02,Widget A,Electronics,3.0,50.0,150.0,GER
1,2023-01-03,Widget B,Electronics,5.0,70.0,350.0,GER
2,2023-01-05,Widget C,Home Appliances,1.0,200.0,200.0,GER
3,2023-01-06,Widget D,Clothing,10.0,30.0,300.0,GER
4,2023-01-07,Widget E,Clothing,2.0,100.0,200.0,GER
5,2023-01-09,Widget F,Home Appliances,4.0,150.0,600.0,GER
6,2023-01-10,Widget G,Electronics,6.0,80.0,480.0,GER
7,2023-01-12,Widget H,Clothing,8.0,40.0,320.0,GER
8,2023-01-13,Widget I,Home Appliances,2.0,250.0,500.0,GER
9,2023-01-15,Widget J,Electronics,7.0,60.0,420.0,GER
15,2023-01-23,Widget F,Home Appliances,6.0,150.0,900.0,GER
16,2023-01-25,Widget G,Electronics,4.0,80.0,320.0,GER
17,2023-01-26,Widget H,Clothing,7.0,40.0,280.0,GER
18,2023-01-27,Widget I,Home Appliances,3.0,250.0,750.0,GER
19,2023-01-29,Widget J,Electronics,8.0,60.0,480.0,GER
20,2023-01-29,Widget G,Clothing,NaN,80.0,NaN,NaN

### Merge

In [47]:
# Creating DataFrame df2
df3 = pd.DataFrame ({
    'ID': [6, 7, 8, 9, 10],
    'Name': ['Fay', 'Gale', 'Harry', 'Ivy', 'Jack']
})

merged_df = pd.concat([df1, df3], ignore_index=True)    # ignore_index=True resets the index column

merged_df

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    Diana
4   5      Eva
5   6      Fay
6   7     Gale
7   8    Harry
8   9      Ivy
9  10     Jack

### Subsetting

In [48]:
# Select a single row
first_row = my_df.iloc[0]

first_row

Date            2023-01-02
Product           Widget A
Category       Electronics
Units Sold               3
Unit Price              50
Total Sales            150
Location               GER
Name: 0, dtype: object

- - - -

## Joining DataFrames <a class="anchor" id="joindata"></a>

### Rules for the `on` keyword argument:

* A single string if joining on one column with the same name, e.g., `on='id'`.
* A list of strings if joining on multiple columns with the same name, e.g., `on=['id1', 'id2']`.
* For joining on columns with different names in the two dataframes, use the `left_on` and `right_on` keyword arguments. For example, to join on dataframe `df1`'s column `'a'` and dataframe `df2`'s column `'b'`, use `left_on='a'` and `right_on='b'`.

```python
import pandas as pd

# Example usage:
df_merged = pd.merge(left=df1, right=df2, on='id')
df_merged = pd.merge(left=df1, right=df2, on=['id1', 'id2'])
df_merged = pd.merge(left=df1, right=df2, left_on='a', right_on='b')

In [49]:
# inner join by default, same values are joined but also missing is joined

merged_inner = pd.merge(left=df1, right=df2, how='inner', on='ID')

merged_inner

   ID     Name  Age
0   3  Charlie   25
1   4    Diana   30
2   5      Eva   35

In [50]:
merged_left = pd.merge(left=df1, right=df2, how='left', on='ID')

merged_left

   ID     Name   Age
0   1    Alice   NaN
1   2      Bob   NaN
2   3  Charlie  25.0
3   4    Diana  30.0
4   5      Eva  35.0

In [51]:
merged_right = pd.merge(left=df1, right=df2, how='right', on='ID')

merged_right

   ID     Name  Age
0   3  Charlie   25
1   4    Diana   30
2   5      Eva   35
3   6      NaN   40
4   7      NaN   45

In [52]:
merged_outer = pd.merge(left=df1, right=df2, how='outer', on='ID')

merged_outer

   ID     Name   Age
0   1    Alice   NaN
1   2      Bob   NaN
2   3  Charlie  25.0
3   4    Diana  30.0
4   5      Eva  35.0
5   6      NaN  40.0
6   7      NaN  45.0

- - - -

# CSV <a class="anchor" id="csv"></a>

CSV (Comma-Separated Values) files are a common file format used to store tabular data. Python provides various methods for reading and writing CSV files, with Pandas offering a straightforward approach. With Pandas, you can easily read a CSV file into a DataFrame using the read_csv() function, perform data manipulation and analysis, and then save the results back to a CSV file if needed.

- - -

## Reading data from a .csv file <a class="anchor" id="csv_reading"></a> <a class="anchor" id="readdata"></a>

Reading a .csv file without a header into a dataframe is the main feature. Afterwards, all pandas functionality can be used.
```python
import pandas as pd

# Read the CSV without a header
df = pd.read_csv('file.csv', header=None)

# Setting a string header while reading
df = pd.read_csv('file.csv', header=None, names=['col1', 'col2'])

Apart from reading data, the `read_csv` function has some other interesting parameters concerning options for file layout and parsing. Especially interesting are:
* File layout: `skiprows`, `skipfooter`, and `usecols`
* Parsing options: `delimiter`, `decimal`, and `parse_dates`


### Markdown Cell 2:

```python
# Example of reading a .csv file with additional parameters
df_example = pd.read_csv('data/Chicago_Temperatures.csv', 
                         skiprows=1,  # Skip the first row
                         delimiter=',',  # Specify the delimiter, default is ',' 
                         decimal='.',  # Specify the decimal delimiter, default is '.'
                         parse_dates=['DateColumn']  # Parse a column as datetime dtype
                        )
```
Read the file `Chicago_Temperatures.csv` from the folder `data`, which should be in the folder of the notebook you are running (in your work directory), or for which the file path has to be stated (be careful with the slash direction).

In [53]:
# Reading a .csv file without a header
df_no_header = pd.read_csv("data/Chicago_Temperatures.csv", header=None)

In [54]:
# Reading a .csv file with a specified header
df_with_header = pd.read_csv("data/Chicago_Temperatures.csv", names=["DateTime", "Temperature"])

Reading a CSV file, providing header names, and specifying column data types and datetime format:

In [3]:
import pandas as pd
from datetime import datetime

# Reading a .csv file with specified header, types, and datetime format
df_with_header_and_dtype = pd.read_csv("data/Chicago_Temperatures.csv", 
                                       names=["DateTime", "Temperature"],
                                       dtype={"DateTime": str, "Temperature": float},
                                       parse_dates=["DateTime"],
                                       date_parser=lambda x: datetime.strptime(x, "%m/%d/%Y %H:%M"))

df_with_header_and_dtype

C:\Users\Nico Gärtner\AppData\Local\Temp\ipykernel_11436\32741598.py:5: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  df_with_header_and_dtype = pd.read_csv("data/Chicago_Temperatures.csv",

              DateTime  Temperature
0  2015-01-01 00:00:00       -7.488
1  2015-01-01 01:00:00       -7.637
2  2015-01-01 02:00:00       -7.813
3  2015-01-01 03:00:00       -7.984
4  2015-01-01 04:00:00       -8.147
5  2015-01-01 05:00:00       -8.221
6  2015-01-01 06:00:00       -8.256
7  2015-01-01 07:00:00       -8.197
8  2015-01-01 08:00:00       -7.428
9  2015-01-01 09:00:00       -6.125
10 2015-01-01 10:00:00       -4.617
11 2015-01-01 11:00:00       -3.123
12 2015-01-01 12:00:00       -1.863
13 2015-01-01 13:00:00       -0.976
14 2015-01-01 14:00:00       -0.522
15 2015-01-01 15:00:00       -0.578
16 2015-01-01 16:00:00       -1.068
17 2015-01-01 17:00:00       -1.300
18 2015-01-01 18:00:00       -1.558
19 2015-01-01 19:00:00       -1.825
20 2015-01-01 20:00:00       -2.051
21 2015-01-01 21:00:00       -2.322
22 2015-01-01 22:00:00       -2.731
23 2015-01-01 23:00:00       -3.165

- - -

## Load and save DataFrames to .csv file<a class="anchor" id="loadsave"></a>

We do not cover all features of the packages. Please refer to their documentation to learn them.

Here we'll load `CSV` to read and write CSV files.

In [56]:
import pandas as pd

# Creating a DataFrame
x = pd.DataFrame({
    'A': [True, False, True],
    'B': [1, 2, None],  # using None for missing data
    'C': [None, 'b', 'c'],
    'D': ['a', None, 'c']
})

x

       A    B     C     D
0   True  1.0  None     a
1  False  2.0     b  None
2   True  NaN     c     c

In [57]:
# Displaying column-wise types
print(x.dtypes)

A       bool
B    float64
C     object
D     object
dtype: object

Next, we'll save x to a CSV file and read the file to see how it was saved:

In [58]:
# Saving x to a CSV file
x.to_csv("x1.csv", index=False)

# Reading and printing the saved CSV file
with open("x1.csv", "r") as file:
    print(file.read())

A,B,C,D
True,1.0,,a
False,2.0,b,
True,,c,c

Finally, we'll read the saved CSV file back into a DataFrame:

In [59]:
# Reading the CSV file into a DataFrame
y = pd.read_csv("x1.csv")

# Displaying the DataFrame
print(y)

       A    B    C    D
0   True  1.0  NaN    a
1  False  2.0    b  NaN
2   True  NaN    c    c

- - - -

# DateTime <a class="anchor" id="datetime"></a>

We would like to analyze the sales regarding the times when sales occurred during the day. First, we need to extract the times from the timestamp.

In Python, using pandas, we can achieve this by accessing the datetime properties directly once the column is in the datetime type. We'll read our sales data, extract relevant time information, and perform some basic analysis on it, such as calculating the sum, mean, and standard deviation of sales at different times.

Additionally, we will create new columns in the DataFrame to hold the extracted hour and day information from the timestamp, which allows for further detailed analysis.

In [60]:
import pandas as pd

# Reading the CSV file with specified header and types
sales = pd.read_csv("data/BerlinSales.csv", 
                    names=["DateTime", "Sales"],
                    dtype={"DateTime": str, "Sales": int},
                    parse_dates=["DateTime"],
                    date_parser=lambda x: pd.to_datetime(x, format="%d.%m.%Y %H:%M"))

# Extracting the hour and day from the DateTime column and creating new columns for them
sales['Hour'] = sales['DateTime'].dt.hour
sales['Day'] = sales['DateTime'].dt.day

# Displaying the DataFrame
sales.head()

C:\Users\Nico Gärtner\AppData\Local\Temp\ipykernel_14340\2217527596.py:4: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  sales = pd.read_csv("data/BerlinSales.csv",

             DateTime  Sales  Hour  Day
0 2020-01-01 10:00:00      2    10    1
1 2020-01-04 10:00:00      4    10    4
2 2020-01-23 10:00:00      5    10   23
3 2020-01-22 10:00:00      3    10   22
4 2020-01-02 20:00:00      6    20    2

With our newly created columns, we can now perform some basic analysis, like calculating the sum, mean, and standard deviation (`std`) of sales at different times of the day.

We will use the `groupby` method for this, allowing us to group our data by the hour of sale, and calculate various statistics for these groups. Additionally, we can also differentiate our analysis for different days.

In [61]:
# Calculating and displaying the sum of Sales grouped by Hour
sales_sum_by_hour = sales.groupby('Hour')['Sales'].sum()
print("Sum of Sales by Hour:")
print(sales_sum_by_hour)

Sum of Sales by Hour:
Hour
10    20
20    26
Name: Sales, dtype: int32

In [62]:
# Calculating and displaying the mean of Sales grouped by Hour
sales_mean_by_hour = sales.groupby('Hour')['Sales'].mean()
print("\nMean of Sales by Hour:")
print(sales_mean_by_hour)

Mean of Sales by Hour:
Hour
10    4.0
20    5.2
Name: Sales, dtype: float64

In [63]:
# Calculating and displaying the standard deviation of Sales grouped by Hour
sales_std_by_hour = sales.groupby('Hour')['Sales'].std()
print("\nStandard Deviation of Sales by Hour:")
print(sales_std_by_hour)

Standard Deviation of Sales by Hour:
Hour
10    1.581139
20    3.114482
Name: Sales, dtype: float64

In [64]:
# Calculating and displaying the sum of Sales grouped by Day and Hour
sales_sum_by_day_hour = sales.groupby(['Day', 'Hour'])['Sales'].sum()
print("\nSum of Sales by Day and Hour:")
print(sales_sum_by_day_hour)

Sum of Sales by Day and Hour:
Day  Hour
1    10       2
2    20       6
3    20       2
4    10       4
5    20      11
14   20       7
22   10       3
23   10      11
Name: Sales, dtype: int32